### ISSUE TITLE
ezreal

### ISSUE THREAD

**Issue by isgood72** [xxEllioTz/PortEnsoul.Aio#1]
========================================
Exception occured! EnsoulSharp might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at EnsoulSharp.Awareness.Utils.ChampionTrack.OnTeleport(AIBaseClient sender, TeleportEventArgs args)
   at EnsoulSharp.SDK.Teleport.OnTeleportEvent.Invoke(AIBaseClient sender, TeleportEventArgs args)
   at EnsoulSharp.SDK.Teleport.FireEvent(AIBaseClient sender, TeleportEventArgs args)
   at EnsoulSharp.SDK.Teleport.OnTeleportInvoke(AIBaseClient sender, AIBaseClientTeleportEventArgs args)
   at EnsoulSharp.AIBaseClient.?????????????????????????????????????????(?????????????????????????????????????????* , ?????????????????????????????????????????* , ?????????????????????????????????????????* )
========================================

**Comment by isgood72** [comment]
use V crash and manamun stuck

**Comment by barillabartus** [comment]
546775u6hgjkgjhk
